[project]
name = "bank-support-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Quvonchbek-Qurbonov", email = "q.qurbonov@newuu.uz" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "fast-langdetect>=1.0.1",
    "fastapi>=0.116.1",
    "groq>=1.7.0",
    "httpx>=0.28.1",
    "lxml>=6.0.1",
    "psycopg[binary]>=3.2.13",
    "pydantic-settings>=2.10.1",
    "qdrant-client>=1.15.1",
    "sentence-transformers>=5.1.0",
    "sqlalchemy>=2.0.43",
    "torch==2.12.1",
    "uvicorn[standard]>=0.35.0",
]

[project.scripts]
bank-support-ai = "bank_support_ai:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
