from typing import List, Annotated

from fastapi import APIRouter, HTTPException, Query
from sqlalchemy import select

from app.api.schemas.schemas import ChatResponse, ChatRequest, Source, ResourceRequest, RelevantResource
from app.service.context import build_context
from app.rag.llm import LLMService, ChatDecision
from app.service.language import LanguageDetectionError, detect_language

import uuid

from app.service.chat_history import append_turn, get_history

router = APIRouter()


@router.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@router.get("/relevants")
def get_relevant_resources(payload: Annotated[ResourceRequest, Query()]) -> List[RelevantResource]:
    try:
        try:
            language = detect_language(payload.question)
        except LanguageDetectionError:
            language = None
        print(f"<<<<<<<<<<<<<<<<<{language}>>>>>>>>>>>>>>>>>>>>>>>>>>")
        context = build_context(
            payload.question,
            language,
        )

        return [
            RelevantResource(
                title=hit.get("title"),
                page_url=hit["page_url"],
                score=float(hit["score"]),
                content=hit["text"],
            )
            for hit in context
        ]

    except RuntimeError as exc:
        raise HTTPException(
            status_code=503,
            detail=str(exc),
        ) from exc


@router.post("/chat", response_model=ChatResponse)
def chat(body: ChatRequest) -> ChatResponse:
    session_id = body.session_id or str(uuid.uuid4())

    try:
        llm = LLMService()
        history = get_history(session_id)

        # LLM call #1: understand the user's request
        decision = llm.analyze(
            body.question,
            history=history,
        )

        # The question is unclear -> ask a clarification question.
        if not decision.question_clear:
            answer = decision.follow_up_question

            append_turn(
                session_id,
                body.question,
                answer,
            )

            return ChatResponse(
                answer=answer,
                sources=[],
                session_id=session_id,
            )

        # No retrieval required -> use the answer generated by LLM #1.
        if not decision.retrieve_information:
            answer = decision.direct_answer

            append_turn(
                session_id,
                body.question,
                answer,
            )

            return ChatResponse(
                answer=answer,
                sources=[],
                session_id=session_id,
            )

        # Retrieval required.
        # IMPORTANT: use the corrected search query, not the raw question.
        context = build_context(
            decision.search_query,
            None,
        )

        # LLM call #2: generate the grounded final answer.
        answer = llm.answer(
            question=body.question,
            search_query=decision.search_query,
            context=context,
            history=history,
        )

        append_turn(
            session_id,
            body.question,
            answer,
        )

        sources = (
            [
                Source(
                    title=context[0].get("title"),
                    page_url=context[0]["page_url"],
                    score=float(context[0]["score"]),
                )
            ]
            if context
            else []
        )

        return ChatResponse(
            answer=answer,
            sources=sources,
            session_id=session_id,
        )

    except RuntimeError as exc:
        raise HTTPException(
            status_code=503,
            detail=str(exc),
        ) from exc

@router.get("/debug/analyze", response_model=ChatDecision)
def debug_analyze(
        question: str = Query(..., min_length=2, max_length=500),
) -> ChatDecision:
    llm = LLMService()

    return llm.analyze(question)